# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c09fadfcf5a06fd246c8364983111dd"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "pos test app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
