api_version = "2026-01"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "c29f531a-0ffb-17e0-fa88-aa0a8e1b984d7d09d60b"
handle = "testblk"
description = "A preact POS UI extension"

# module: path to the file that contains your extension’s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.product-details.action.render"

[[extensions.targeting]]
module = "./src/Block.jsx"
target = "pos.purchase.post.block.render"
